/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package c5;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class SchoolResourceTest {

    @Test
    public void testEmployee() {
        Employee employee = new Employee(1, "John Doe", "Math Teacher", 3000.0, "Math Department");
        
        assertEquals(1, employee.getResourceID());
        assertEquals("John Doe", employee.resourceName);
        assertEquals("Math Teacher", employee.description);
        assertEquals(3000.0, employee.getSalary(), 0.001);
        assertEquals("Math Department", employee.department);
        
        assertEquals("Employee from: Math Department is working right now", employee.work());
    }

    @Test
    public void testEquipment() {
        Equipment equipment = new Equipment(2, "Projector", "High-definition projector", "Room A", true);
        
        assertEquals(2, equipment.getResourceID());
        assertEquals("Projector", equipment.resourceName);
        assertEquals("High-definition projector", equipment.description);
        assertEquals("Room A", equipment.location);
        assertTrue(equipment.isFunctional);
        
        equipment.relocate("Room B");
        assertEquals("Room B", equipment.location);
        
        equipment.repair();
        assertTrue(equipment.isFunctional);
    }

    @Test
    public void testTeachingMaterial() {
        TeachingMaterial material = new TeachingMaterial(3, "Textbook", "Algebra textbook", "Algebra", false);
        
        assertEquals(3, material.getResourceID());
        assertEquals("Textbook", material.resourceName);
        assertEquals("Algebra textbook", material.description);
        assertEquals("Algebra", material.getSubject());
        assertFalse(material.isInUse);
        
        material.checkout();
        assertTrue(material.isInUse);
        
        material.checkin();
        assertFalse(material.isInUse);
        
    }
}

